localization_supervisor:
  ros__parameters:
    start_pose_file: ""
    initial_pose_arm: false
    map_topic: /map
    scan_topic: /scan
    odom_topic: /Odometry
    amcl_pose_topic: /amcl_pose
    odom_frame: camera_init
    base_frame: body
    heartbeat_rate: 10.0
